name: Benchmarks

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      benchmarks:
        description: Comma or space-delimited benchmark IDs, or "default"/"all"
        required: false
        default: default
        type: string

permissions: {}

jobs:
  benchmark:
    uses: mullvad/app-bench/.github/workflows/run-benchmarks.yml@app-bench-rework
    with:
      benchmarks: ${{ inputs.benchmarks || 'default' }}
      manifest-path: benchmarks/Cargo.toml
